#!/bin/bash

# default to production
DEPLOY_ENV=${1:-'production'}

# local site+app vars
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${DIR}/config

cd ${DIR}/..

# clean up compiled .pyc files
find . -name '*.pyc' -delete

source ${VENV_PATH}/bin/activate

pip install -r requirements.txt
pip install -r requirements-dev.txt
pip install -e .

cd docs
rm -rf ./build/html
make html

cd build/html
aws s3 sync . s3://lager-docs/lager-cli/
