#!/bin/bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${DIR}/config
cd ${DIR}/..

export BEFORE_PULL=`git log -n1 | head -n1 | awk {'print $2'}`
system/pull
export AFTER_PULL=`git log -n1 | head -n1 | awk {'print $2'}`

if test "${BEFORE_PULL}" != "${AFTER_PULL}"
then
    system/deploy qa
fi
